### ISSUE TITLE
Getting all zero CIE matrix for GPT-NeoX

### ISSUE THREAD

**Issue by kayoyin** [ericwtodd/function_vectors#8]
Thanks for the great work!
I'm trying to recompute function vectors for GPT-NeoX (and Pythia models using the same setup you have for GPT-NeoX). However, after running `compute_indirect_effect.py`, I get all zero CIE matrices (`indirect_effect.pt`). 

I think this is due to the ablation intervention not working on these models, so clean probs and intervention probs are always equal hence why the difference is always 0.

Other models I tried don't have this issue (GPT2, LLaMa).

Do you know how to make the intervention work for GPT-NeoX models? Thanks!

**Comment by ericwtodd** [comment]
There are some places in the intervention code that use the model name to modify the output. It could be that the intervention wasn't happening so the clean and intervention probs matched. I've updated the code so that it should hopefully work with the Pythia models.

I tested `EleutherAI/pythia-6.9b-deduped` using the following code in a notebook that I placed inside the `src` directory and the indirect effect I got seems to be non-zero. The FV I get using this IE gives decent performance for antonyms in downstream ZS eval. 
Can you try pulling the changes to see if it's now working for you?

```
import os, re, json
import torch, numpy as np
torch.set_grad_enabled(False)

from utils.extract_utils import get_mean_head_activations, compute_function_vector
from utils.intervention_utils import fv_intervention_natural_text, function_vector_intervention
from utils.model_utils import load_gpt_model_and_tokenizer
from utils.prompt_utils import load_dataset, word_pairs_to_prompt_data, create_prompt
from utils.eval_utils import decode_to_vocab, sentence_eval
from compute_indirect_effect import compute_indirect_effect

model_name = 'EleutherAI/pythia-6.9b-deduped'
model, tokenizer, model_config = load_gpt_model_and_tokenizer(model_name)
EDIT_LAYER = 9

dataset = load_dataset('antonym', seed=0)
mean_activations = get_mean_head_activations(dataset, model, model_config, tokenizer)

IE = compute_indirect_effect(dataset, mean_activations, model, model_config, tokenizer, 10, 2)
FV, top_heads = compute_function_vector(mean_activations, IE, model, model_config, 10)
zs_results = n_shot_eval(dataset, FV, EDIT_LAYER, 0,model, model_config, tokenizer)
```


Is there a particular task that you're getting CIE of 0's?

**Comment by kayoyin** [comment]
Thanks a lot for looking into this so quickly! Pulling the changes resolved the issue, thanks!
